name: github-actions
on: [push]


jobs:
  check:
    name: dcm-action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: dcm
        uses: dart-code-checker/dart-code-metrics-action@v2
        with:
          github_token: "${{ secrets.TOKEN }}"
          # github_pat: "${{ secrets.GITHUB_TOKEN }}"
          pull_request_comment: true 