name: github-actions
on: 
  pull_request:
    branches:    
      - master
    types: [opened]

jobs:
  check:
    name: dcm-action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: dcm
        uses: dart-code-checker/dart-code-metrics-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        pull_request_comment: true